package com.kindsundev.expense.manager.common

enum class Status {
    WRONG_DATA_NULL,
    WRONG_EMAIL_EMPTY,
    WRONG_PASSWORD_EMPTY,
    WRONG_EMAIL_PASSWORD_EMPTY,
    WRONG_EMAIL_PATTERN,
    WRONG_PASSWORD_LENGTH,
    WRONG_NAME_LENGTH,
    VALID_EMAIL,
    VALID_DATA
}