package com.kindsundev.expense.manager.common

enum class Status {
    WRONG_EMAIL_EMPTY,
    WRONG_PASSWORD_EMPTY,
    WRONG_EMAIL_PASSWORD_EMPTY,
    WRONG_EMAIL_PATTERN,
    WRONG_PASSWORD_LENGTH,
    WRONG_NAME_EMPTY,
    WRONG_NAME_SHORT,
    WRONG_NAME_LONG,
    WRONG_NAME_HAS_DIGITS,
    WRONG_HAS_SPECIAL_CHARACTER,
    WRONG_BALANCE_EMPTY,
    VALID_DATA
}